language: ruby
sudo: false
rvm:
    - 2.1.1
jdk:
    - openjdk8
before_install:
 - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda install --file ./_scripts/requirements.txt
before_script: python ./_scripts/gscrawler.py -u 6j85aJMAAAAJ -o ./_includes/publications.md || true
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push
branches:
  only:
      - master
env:
  global:
      - secure: Xrgw5mrNl5Y2RQ3fiJJ4DN9nX0ul1ZpYBSXmdoGm7jMP9FKnToUS/GFxW1f8Chdx3sn7bS7YqqrV2ArhEr6OtTk+Yw2H9DgONfUwE5Bi/j9Lk70YFZFSFyzyLZlmY9ngUPkpsujWsZ1Rd+fUVvSWxqL2tbDlJqO+cQCOqdFFyww=
      - secure: ct5tba4mchGCoqp3YF5ahcVJ+UdunvGfi1aFP0Miu6lwjvTxUv2NRBSSZfMVCfSRyzX+QLEKtzXs+L4+uLyg0wrxS+3TU+wV+Tqz94awR8czQufUDaFYY9eWW45ZLG9Y9+OfkGtUtlqnJYbiYwx5NCE7Zm9ce6awPyXPidmIRa0=
